backend:
  name: git-gateway
  branch: main
  identity_url: https://your-site.netlify.app/.netlify/identity
  gateway_url: https://your-site.netlify.app/.netlify/functions
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
