backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "rings"
    label: "Rings"
    folder: "content/rings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Ring Name", name: "title", widget: "string" }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" }, min: 3, max: 6 }
      - label: "Collection"
        name: "ring_collection"
        widget: "select"
        options: ["Cuban Link", "Western", "Faith"]
      - label: "Base Band Height"
        name: "band_height"
        widget: "select"
        options:
          - { label: "Small (3mm) – $30", value: "30" }
          - { label: "Medium (5mm) – $60", value: "60" }
          - { label: "Large (8mm) – $90", value: "90" }
      - label: "Material"
        name: "material"
        widget: "select"
        default: "Silver"
        options:
          - { label: "Silver", value: "silver" }
      - label: "Add-Ons"
        name: "addons"
        widget: "object"
        fields:
          - { label: "Rope Braid (qty × $5)", name: "rope_braid", widget: "number", default: 0, min: 0 }
          - { label: "Small Cuban Link (qty × $5)", name: "small_cuban", widget: "number", default: 0, min: 0 }
          - { label: "Large Cuban Link (qty × $30)", name: "large_cuban", widget: "number", default: 0, min: 0 }
          - { label: "Channels (qty × $4)", name: "channels", widget: "number", default: 0, min: 0 }
          - { label: "Beading (+$30)", name: "beading", widget: "boolean", default: false }
          - { label: "Cut-Outs (qty × $4)", name: "cutouts", widget: "number", default: 0, min: 0 }
          - label: "Pattern (+$35)"
            name: "pattern"
            widget: "select"
            options:
              - { label: "None", value: "none" }
              - { label: "Western", value: "western" }
              - { label: "Floral", value: "floral" }
              - { label: "Aztec", value: "aztec" }
          - { label: "Symbols (qty × $4)", name: "symbols", widget: "number", default: 0, min: 0 }
      - label: "Engraving / Embossing"
        name: "engraving"
        widget: "object"
        fields:
          - { label: "Inside Text", name: "inside", widget: "text", required: false }
          - { label: "Outside Text", name: "outside", widget: "text", required: false }
      - { label: "Product Description", name: "body", widget: "markdown", required: false }
