backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "cuban_rings"
    label: "Cuban Link Rings"
    folder: "collections/rings/cuban"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "faith_rings"
    label: "Faith Rings"
    folder: "collections/rings/faith"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "western_rings"
    label: "Western Rings"
    folder: "collections/rings/western"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "faith_charms"
    label: "Faith Charms"
    folder: "collections/charms/faith"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "western_charms"
    label: "Western Charms"
    folder: "collections/charms/western"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "medical_charms"
    label: "Medical Charms"
    folder: "collections/charms/medical"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "charm_bracelets"
    label: "Charm Bracelets"
    folder: "collections/bracelets/charm"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "cuff_bracelets"
    label: "Cuff Bracelets"
    folder: "collections/bracelets/cuff"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "bronze_money_clips"
    label: "Bronze Money Clips"
    folder: "collections/bronze/money_clips"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "bronze_belt_buckles"
    label: "Bronze Belt Buckles"
    folder: "collections/bronze/belt_buckles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "bronze_cowboy_toothpicks"
    label: "Bronze Cowboy Toothpicks"
    folder: "collections/bronze/cowboy_toothpicks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "bronze_keychains"
    label: "Bronze Keychains"
    folder: "collections/bronze/keychains"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "bronze_mini_ranch_brands"
    label: "Bronze Mini Ranch Brands"
    folder: "collections/bronze/mini_ranch_brands"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "earrings_collection"
    label: "Earrings"
    folder: "earrings"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "pendants_collection"
    label: "Pendants"
    folder: "pendants"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
